root_path: ""
bands: [1, 2, 3, 4, 5, 6, 7] #["Red", "Green", "Blue", "B08", "B08a", "B11", "B12"]
input_nbr_S2: 7
input_nbr_S1: 2
num_classes: 2
epochs: 2
batch_size: 16
learning_rate: 0.00005
weight_decay: 0.02
deforest_weight: 0.9
loss_fn: "CrossEntropyLoss"
update_cm_interval: 1
iou_threshold: 0.05
dilate_mask: True
mode: "train_selected"
model_name: "ChangeformerV8"
model_num: 10
seed: 42
file_type: "tif"
sentinel_type: "both"
patch_size: 224
kernel_size: 3
dropout: 0.2
patience: 15
scheduler: "StepLR"
comment: "3 stages model, no augmentation"
